"use client";
import NextTopLoader from "nextjs-toploader";
import { Libre_Franklin } from "next/font/google";
import "./globals.css";
import { LoadingContext } from "@/lib/global/context/context";
import { useState } from "react";
import ResponsiveNav from "@/components/common/NavBar/ResponsiveNav";
import Footeer from "@/components/common/Footer/Footer";

const halvetica = Libre_Franklin({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [loading, setLoading] = useState(false);
  function updateLoading(value: boolean) {
    setLoading(value);
  }
  return (

    <LoadingContext.Provider value={{ loading, setter: updateLoading }}>
      <html lang="en">
        <body className={halvetica.className}>
          <ResponsiveNav />
          <NextTopLoader />
          {children}
          <Footeer />
        </body>
      </html>
    </LoadingContext.Provider>
  );
}
